## Arrays in Python

1. Using Array module 

In [1]:
import array

In [2]:
arr = array.array('i', [10, 20, 30, 40, 50])
print(arr)
print(type(arr))

array('i', [10, 20, 30, 40, 50])
<class 'array.array'>


In [8]:
arr2 = array.array('i', [60,70,80])
print(arr2)

array('i', [60, 70, 80])


In [3]:
# to access
arr[2]

30

In [4]:
# traversing 
for i in arr:
      print(i, end=" ")

10 20 30 40 50 

In [5]:
# insertion 
arr.insert(3, 35)
print(arr)

array('i', [10, 20, 30, 35, 40, 50])


In [6]:
# deletion
arr.remove(30)
print(arr)

array('i', [10, 20, 35, 40, 50])


In [7]:
# updation 
arr[2] = 30
print(arr)

array('i', [10, 20, 30, 40, 50])


In [9]:
# sorting 

arr3 = array.array('i', [5,3,8,5,9,1])
print(arr3)

array('i', [5, 3, 8, 5, 9, 1])


In [12]:
sorted(arr3) #- it will give list 

# for array
sorted_arr3 = array.array('i', sorted(arr3))
print(sorted_arr3)

array('i', [1, 3, 5, 5, 8, 9])


In [16]:
# merging
merge = arr + arr2

In [21]:
# splitting 
ix = int(len(merge) / 2)

In [22]:
merge[:ix]

array('i', [10, 20, 30, 40])

In [23]:
merge[ix:]

array('i', [50, 60, 70, 80])

2. Using Numpy

In [24]:
import numpy as np

In [25]:
np1 = np.array([10,20,30,40,50])
np2 = np.array([60,70,80])    

In [26]:
np1[3]

40

In [27]:
for i in np1:
      print(i, end=" ")

10 20 30 40 50 

In [28]:
np.insert(np1, 3, 35)

array([10, 20, 30, 35, 40, 50])

In [29]:
np.delete(np1, 3)

array([10, 20, 30, 50])

In [32]:
np1[2] = 35
print(np1)

[10 20 35 40 50]


In [34]:
np3 = np.array([4,9,6,2,7,5])
np3

array([4, 9, 6, 2, 7, 5])

In [36]:
np.sort(np3)

array([2, 4, 5, 6, 7, 9])

In [39]:
merge = np.concatenate((np1, np2))
merge

array([10, 20, 35, 40, 50, 60, 70, 80])

In [41]:
split1, split2 = np.array_split(merge, 2)      

In [42]:
split1

array([10, 20, 35, 40])

In [43]:
split2

array([50, 60, 70, 80])